
```{r}
a <- c(1, 3, elementName=7)
a[[1]]
a[["elementName"]]
```

```{r}
a[[elementName]] 
a[[`elementName`]]
```

```{r}
targetName <- "elementName"
a[[targetName]] # name call on targetName
```

***

ONLY list 

list[[x]]
list$x

```{r}
sample_data <- list(
  "observation1"=list(54, "male", "north", 100), 
  "observation2"=list(32, "female", "south", 25), 
  "observation3"=list(28, "female", "east", NA), 
  "observation4"=list(20, "male", "east", 77)
)
```

```{r}
sample_data[["observation4"]]
sample_data$"observation4"
sample_data$observation4
sample_data$`observation4`
```

```{r}
sample_data$observation4
```

```{r}
list(
  Compulsory = list(
    "Principle of Economics",
    "Calculus",
    "Accounting"
  ),
  Selective = list(
    "Philosophy",
    "Chinese Literature"
  )
)

```

```{r}
list(
  list(
  name="Gianandrea Noseda conducts Schumann and Mendelssohn — With Mikhail Pletnev",
  time="2021, Oct, 01",
  program=list(
    "Robert Schumann, Piano Concerto in A Minor, Op. 54",
    "Felix Mendelssohn-Bartholdy, Symphony No. 4 in A Major, Op. 90, Italian"
  )
), 
  list(
  name="Gianandrea Noseda conducts Schumann and Mendelssohn — With Mikhail Pletnev",
  time="2021, Oct, 01",
  program=list(
    "Robert Schumann, Piano Concerto in A Minor, Op. 54",
    "Felix Mendelssohn-Bartholdy, Symphony No. 4 in A Major, Op. 90, Italian"
  )
)
)
```

***

Programming for Data Science, Wed. Session 5-6, IT-B1-06

* course_name: Programming for Data Science
* time: Wed. Session 5-6
* place: IT-B1-06

```{r}
list(
  course_name="Programming for Data Science",
  time="Wed. Session 5-6",
  place="IT-B1-06"
) -> course1
```

```{r}
list(
  course_name="Statistics",
  time="每週四2~4",
  place="法2F16"
) -> course2
```


```{r}
two_courses <- list(
  course1,
  course2
)
```


1. 
  * course_name
  * time
  * place
2.
  * course_name
  * time
  * place
  
***

```{r}
list(
  time= "Mon 5~7",
  place="business1F09"
) -> Calculus

list(
  time="Fri 5~6",
  place="law2F28"
) -> Politics
```

list of these two courses
```{r}
list(
  "Calculus"= list(
  time= "Mon 5~7",
  place="business1F09"
),
  "Politics"= list(
  time="Fri 5~6",
  place="law2F28"
)
)
```

 * Calculus: Calculus
 
 * Politics: Politics

***

1. 
  * course_name
  * time
  * place
2.
  * course_name
  * time
  * place

```{r}
list(
  list(name = "principle of economic",
       time =  "Wednesday",
       place ="social science college"), 
  list(name = "accounting",
       time = "Thusday" ,
       place = "Business college") 
)
```

***

 * Principles_of_Economics
   * classroom
   * day
   
 * Calculus
   * classroom
   * day

```{r}
list(
  Principles_of_Economics = list(
    classroom = "social science 104" , 
    day = "Wednesday session 2-4 and Thursday sessiom 2-4"
  ),
  Calculus = list(
    classroom = "social science 104" , 
    day = "Monday session 5-7"
  )
)
```

```{r}
list(
  list(course_name="principle of economics",
  time="Wednesday10AM",
  place="Social Sciences105"),

 list(course_name="accounting",
      time="Tuesday13PM",
   place=" business2F11")
)

```

```{r}

```

