
```{r}
list(
  "milk", 
  "apple", 
  "pork"
)[[1]]
```

```{r}
list(
  Compulsory = 
    c("Principle of Economics", 
      "Calculus", 
      "Accounting"), # use c( ) only if values are of the same type
  Selective = 
    list("Philosophy", 
      "Chinese Literature")
)
```


## import JSON
F1
```{r}
# Observation by observation
concerts_obo <-
  jsonlite::fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=17", simplifyDataFrame = FALSE)

# Feature by feature
concerts_fbf <-
  jsonlite::fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=17", simplifyDataFrame = TRUE)
```

```{r}
concerts_fbf <- list(
  version=c(...),
  UID=c(...),
  title=c(....)
)
```

## 3.2

```{r}
[[1]]
[["element name"]]
```

```{r}
[ c(1, 2, 5) ]
[ c("name1", "name2")]
```



```{r}
JohnsFamily <-
  list(
    name = "John", 
    age = 35,
    spouse = list(
      name = "Mary", 
      age = 32),
    children = list(
      list(
        name = "Bill", 
        age = 5),
      list(
        name = "Jane", 
        age = 3)
    )
  )
```

```{r}
# checking how many element values
length(JohnsFamily)
length(list(
    name = "John", 
    age = 35,
    spouse = list(
      name = "Mary", 
      age = 32),
    children = list(
      list(
        name = "Bill", 
        age = 5),
      list(
        name = "Jane", 
        age = 3)
    )
  ))

# checking element names
names(JohnsFamily)
```


```{r}
fncallExample <- list("John", 35, covid19Positive=FALSE)
length(fncallExample)
names(fncallExample)
```


```{r}
Sys.Date() # show the date today
```

```{r}
Sys.Date
```

```{r}
car() # driving a car; function call
```

```{r}
car # look inside a car to see how it is built
```

```{r}
example1 <- JohnsFamily[c(1,2)] # also a list
JohnsFamily[c("name", "age")]
```

```{r}
source2 <- c(2, 29, 3, 7)
example2 <- source2[c(2,4)]
```


```{r}
JohnsFamily["age"] # no no 
JohnsFamily[2] # no no
```

```{r}
JohnsFamily[["age"]]
JohnsFamily[[2]]
```

```{r}
[[1]]$name[c(1,3,5)]
```


```{r}
concerts_sampled <- concerts_obo#retrieval
```


```{r}

concerts_sampled <- concerts_obo[c(3,5)] 
firstShowInfo <- concerts_obo[[2]][["showInfo"]][[1]][c("time","location")]
firstShowInfo <- concerts_obo[[2]]$showInfo[[1]][c("time","location")]

```






